import fs from 'fs';
import path from 'path';

import * as paths from './paths';

const DEFAULTS_DIR = path.join(__dirname, '..', 'defaults');

/** Root of the running installation, i.e. the folder holding package.json. */
const PACKAGE_ROOT = path.resolve(__dirname, '..', '..');

/**
 * How the generated tsconfig identifies itself. Remove the line and the file
 * becomes the user's: it is never written again.
 */
const GENERATED_MARKER = 'Generated by ronsel';

/** The marker the file carried before the package was renamed. */
const LEGACY_MARKER = 'Generated by @lab34/flows';

/** The type declarations an application is written against. */
const typeDeclarations = () => {
  const built = path.join(PACKAGE_ROOT, 'dist', 'index.d.ts');

  // Running from source (development, or the test suite) there is no dist yet
  return fs.existsSync(built) ? built : path.join(PACKAGE_ROOT, 'src', 'index.ts');
};

/**
 * Where the `@types` this installation carries actually live. It cannot be
 * assumed to be `<package>/node_modules/@types`: npm hoists dependencies, so
 * in a normal install they sit next to the package rather than under it.
 */
const typesDirectory = () => {
  try {
    // .../node_modules/@types/node/package.json -> .../node_modules/@types
    const manifest = require.resolve('@types/node/package.json', { paths: [PACKAGE_ROOT] });
    return path.dirname(path.dirname(manifest));
  }
  catch {
    return path.join(PACKAGE_ROOT, 'node_modules', '@types');
  }
};

/** The tsconfig that makes an editor understand the applications. */
const typeScriptConfig = () => {
  const declarations = typeDeclarations().split(path.sep).join('/');
  const types = typesDirectory().split(path.sep).join('/');

  const config = {
    compilerOptions: {
      target: 'ES2022',
      lib: ['ES2023'],
      module: 'CommonJS',
      moduleResolution: 'Node10',
      esModuleInterop: true,
      allowSyntheticDefaultImports: true,
      resolveJsonModule: true,
      strict: true,
      // Applications are transpiled, never type checked, when they run: types
      // are here to help while writing them, not to stand between a flow and
      // being run. Annotate what is worth annotating and leave the rest.
      noImplicitAny: false,
      useUnknownInCatchVariables: false,
      skipLibCheck: true,
      noEmit: true,
      baseUrl: '.',
      paths: {
        'ronsel': [declarations],
        // The names the package was published under before the rename
        '@lab34/flows': [declarations],
        'lab34-flows': [declarations]
      },
      typeRoots: [types]
    },
    include: ['applications/**/*.ts']
  };

  return [
    '/*',
    ` * ${GENERATED_MARKER}. It points your editor at the types of the`,
    ' * installed package so applications get completion and checking.',
    ' *',
    ' * It is rewritten on every start while this notice is here -- which is',
    ' * what keeps the paths below correct when the package moves or is',
    ' * upgraded. Delete the notice to take ownership of the file.',
    ' */',
    JSON.stringify(config, null, 2),
    ''
  ].join('\n');
};

/**
 * Write the tsconfig.json that gives the applications editor support.
 *
 * Applications are TypeScript but live outside any installation of this
 * package, so nothing tells an editor where `ronsel` is. This does,
 * with absolute paths into the installation that is running -- which is why
 * it is refreshed on every start rather than written once.
 */
const ensureTypeScriptConfig = async () => {
  try {
    const configPath = await paths.contextDir(['tsconfig.json']);

    if (fs.existsSync(configPath)) {
      const current = fs.readFileSync(configPath, 'utf8');

      // The user took the file over: leave it alone
      if (!current.includes(GENERATED_MARKER) && !current.includes(LEGACY_MARKER)) { return; }

      const wanted = typeScriptConfig();
      if (current !== wanted) {
        fs.writeFileSync(configPath, wanted, 'utf8');
      }

      return;
    }

    fs.mkdirSync(path.dirname(configPath), { recursive: true });
    fs.writeFileSync(configPath, typeScriptConfig(), 'utf8');
  }
  catch (ex) {
    // Editor support is a convenience: never let it stop the tool
    console.error('Could not write tsconfig.json for the applications:', ex.message);
  }
};

/**
 * Seed the user's context directory (~/ronsel by default, or the
 * --context directory) with the bundled example applications and flows.
 *
 * Copies are conservative: an example is only copied when its destination
 * does not exist yet, so user modifications and deletions of individual
 * files inside an already-copied example are preserved.
 */
const ensureDefaults = async () => {
  try {
    // Make sure the base folders exist
    const applicationsDir = await paths.contextDir(['applications']);
    const flowsDir = await paths.contextDir(['flows']);
    fs.mkdirSync(applicationsDir, { recursive: true });
    fs.mkdirSync(flowsDir, { recursive: true });

    // Refreshed every start, unlike the examples below
    await ensureTypeScriptConfig();

    // Only seed once: users must be able to delete examples without them
    // coming back on every start
    const markerPath = await paths.contextDir(['.examples-seeded']);
    if (fs.existsSync(markerPath)) {
      return;
    }

    // Example applications: copy each app folder if missing
    const defaultAppsDir = path.join(DEFAULTS_DIR, 'applications');
    if (fs.existsSync(defaultAppsDir)) {
      for (const appName of fs.readdirSync(defaultAppsDir)) {
        const source = path.join(defaultAppsDir, appName);
        if (!fs.statSync(source).isDirectory()) { continue; }

        const destination = path.join(applicationsDir, appName);
        if (fs.existsSync(destination)) { continue; }

        fs.cpSync(source, destination, { recursive: true });
        console.log(`Seeded example application: ${appName}`);
      }
    }

    // Example flows: copy each file if missing (keeping folder structure)
    const defaultFlowsDir = path.join(DEFAULTS_DIR, 'flows');
    if (fs.existsSync(defaultFlowsDir)) {
      const copyFlows = (dir, relative = '') => {
        for (const item of fs.readdirSync(dir)) {
          const source = path.join(dir, item);
          const itemRelative = path.join(relative, item);

          if (fs.statSync(source).isDirectory()) {
            copyFlows(source, itemRelative);
            continue;
          }

          const destination = path.join(flowsDir, itemRelative);
          if (fs.existsSync(destination)) { continue; }

          fs.mkdirSync(path.dirname(destination), { recursive: true });
          fs.copyFileSync(source, destination);
          console.log(`Seeded example flow: ${itemRelative}`);
        }
      };

      copyFlows(defaultFlowsDir);
    }

    fs.writeFileSync(markerPath, JSON.stringify({ seededAt: new Date().toISOString() }, null, 2));
  }
  catch (ex) {
    // Seeding must never prevent the tool from starting
    console.error('Could not seed default examples:', ex.message);
  }
};

export {
  ensureDefaults,
  ensureTypeScriptConfig
};
