import fs from 'fs';
import path from 'path';

import * as paths from './paths';

const DEFAULTS_DIR = path.join(__dirname, '..', 'defaults');

/** Root of the running installation, i.e. the folder holding package.json. */
const PACKAGE_ROOT = path.resolve(__dirname, '..', '..');

/**
 * How the generated tsconfig identifies itself. Remove the line and the file
 * becomes the user's: it is never written again.
 */
const GENERATED_MARKER = 'Generated by ronsel';

/** The marker the file carried before the package was renamed. */
const LEGACY_MARKER = 'Generated by @lab34/flows';

/** What a folder holds when it is a context of ours rather than any folder. */
const CONTEXT_ENTRIES = ['flows', 'applications', 'test-runs', 'views.yaml', '.examples-seeded'];

/** `.DS_Store` is the Finder's, not the user's: a folder with only it is empty. */
const IGNORED_ENTRIES = ['.DS_Store'];

/**
 * Whether a directory holds nothing of anybody's.
 *
 * This is the whole question the first run turns on: an empty folder becomes a
 * context, with the examples and the folders in it, and a folder with
 * something in it is served exactly as it is.
 *
 * @param {string} directory
 * @returns {boolean} true when the directory is missing or has no entries
 */
const isEmptyDirectory = (directory: string): boolean => {
  if (!fs.existsSync(directory)) { return true; }

  try {
    return fs.readdirSync(directory).every(entry => IGNORED_ENTRIES.includes(entry));
  }
  catch {
    return false;
  }
};

/**
 * Whether a directory is a context of ours, i.e. one we may write into.
 *
 * An empty one is about to become one; one that already holds flows or
 * applications is one. Anything else is somebody's own folder that happens to
 * be where the command was run, and nothing of ours belongs in it.
 *
 * @param {string} directory
 * @returns {boolean}
 */
const isContextDirectory = (directory: string): boolean => {
  if (isEmptyDirectory(directory)) { return true; }

  return CONTEXT_ENTRIES.some(entry => fs.existsSync(path.join(directory, entry)));
};

/** The type declarations an application is written against. */
const typeDeclarations = () => {
  const built = path.join(PACKAGE_ROOT, 'dist', 'index.d.ts');

  // Running from source (development, or the test suite) there is no dist yet
  return fs.existsSync(built) ? built : path.join(PACKAGE_ROOT, 'src', 'index.ts');
};

/**
 * Where the `@types` this installation carries actually live. It cannot be
 * assumed to be `<package>/node_modules/@types`: npm hoists dependencies, so
 * in a normal install they sit next to the package rather than under it.
 */
const typesDirectory = () => {
  try {
    // .../node_modules/@types/node/package.json -> .../node_modules/@types
    const manifest = require.resolve('@types/node/package.json', { paths: [PACKAGE_ROOT] });
    return path.dirname(path.dirname(manifest));
  }
  catch {
    return path.join(PACKAGE_ROOT, 'node_modules', '@types');
  }
};

/** The tsconfig that makes an editor understand the applications. */
const typeScriptConfig = () => {
  const declarations = typeDeclarations().split(path.sep).join('/');
  const types = typesDirectory().split(path.sep).join('/');

  const config = {
    compilerOptions: {
      target: 'ES2022',
      lib: ['ES2023'],
      module: 'CommonJS',
      moduleResolution: 'Node10',
      esModuleInterop: true,
      allowSyntheticDefaultImports: true,
      resolveJsonModule: true,
      strict: true,
      // Applications are transpiled, never type checked, when they run: types
      // are here to help while writing them, not to stand between a flow and
      // being run. Annotate what is worth annotating and leave the rest.
      noImplicitAny: false,
      useUnknownInCatchVariables: false,
      skipLibCheck: true,
      noEmit: true,
      baseUrl: '.',
      paths: {
        'ronsel': [declarations],
        // The names the package was published under before the rename
        '@lab34/flows': [declarations],
        'lab34-flows': [declarations]
      },
      typeRoots: [types]
    },
    include: ['applications/**/*.ts']
  };

  return [
    '/*',
    ` * ${GENERATED_MARKER}. It points your editor at the types of the`,
    ' * installed package so applications get completion and checking.',
    ' *',
    ' * It is rewritten on every start while this notice is here -- which is',
    ' * what keeps the paths below correct when the package moves or is',
    ' * upgraded. Delete the notice to take ownership of the file.',
    ' */',
    JSON.stringify(config, null, 2),
    ''
  ].join('\n');
};

/**
 * Write the tsconfig.json that gives the applications editor support.
 *
 * Applications are TypeScript but live outside any installation of this
 * package, so nothing tells an editor where `ronsel` is. This does,
 * with absolute paths into the installation that is running -- which is why
 * it is refreshed on every start rather than written once.
 */
const ensureTypeScriptConfig = async () => {
  try {
    const configPath = await paths.contextDir(['tsconfig.json']);
    const root = await paths.contextDir([]);

    // A folder that is not a context of ours never gets a file of ours: the
    // context can be any directory the command was run from now, and dropping
    // a tsconfig.json into somebody's project would be a surprise
    if (!fs.existsSync(configPath) && !isContextDirectory(root)) { return; }

    if (fs.existsSync(configPath)) {
      const current = fs.readFileSync(configPath, 'utf8');

      // The user took the file over: leave it alone
      if (!current.includes(GENERATED_MARKER) && !current.includes(LEGACY_MARKER)) { return; }

      const wanted = typeScriptConfig();
      if (current !== wanted) {
        fs.writeFileSync(configPath, wanted, 'utf8');
      }

      return;
    }

    fs.mkdirSync(path.dirname(configPath), { recursive: true });
    fs.writeFileSync(configPath, typeScriptConfig(), 'utf8');
  }
  catch (ex) {
    // Editor support is a convenience: never let it stop the tool
    console.error('Could not write tsconfig.json for the applications:', ex.message);
  }
};

/**
 * Make a context out of the directory this run works in.
 *
 * Only an empty directory is furnished: it gets the `applications` and `flows`
 * folders and the bundled examples, which is what a first run needs to have
 * something to look at. A directory with anything in it is served as it is --
 * an existing context has its own flows already, and any other folder is not
 * ours to fill.
 *
 * Copies are conservative: an example is only copied when its destination
 * does not exist yet, so user modifications and deletions of individual
 * files inside an already-copied example are preserved.
 */
const ensureDefaults = async () => {
  try {
    const root = await paths.contextDir([]);

    // Nothing is created inside a directory that already holds something.
    // An existing context still gets its tsconfig refreshed, so editor
    // support follows the installation when the package is upgraded
    if (!isEmptyDirectory(root)) {
      await ensureTypeScriptConfig();
      return;
    }

    // Make sure the base folders exist
    const applicationsDir = await paths.contextDir(['applications']);
    const flowsDir = await paths.contextDir(['flows']);
    fs.mkdirSync(applicationsDir, { recursive: true });
    fs.mkdirSync(flowsDir, { recursive: true });

    // Refreshed every start, unlike the examples below
    await ensureTypeScriptConfig();

    const markerPath = await paths.contextDir(['.examples-seeded']);

    // Example applications: copy each app folder if missing
    const defaultAppsDir = path.join(DEFAULTS_DIR, 'applications');
    if (fs.existsSync(defaultAppsDir)) {
      for (const appName of fs.readdirSync(defaultAppsDir)) {
        const source = path.join(defaultAppsDir, appName);
        if (!fs.statSync(source).isDirectory()) { continue; }

        const destination = path.join(applicationsDir, appName);
        if (fs.existsSync(destination)) { continue; }

        fs.cpSync(source, destination, { recursive: true });
        console.log(`Seeded example application: ${appName}`);
      }
    }

    // Example flows: copy each file if missing (keeping folder structure)
    const defaultFlowsDir = path.join(DEFAULTS_DIR, 'flows');
    if (fs.existsSync(defaultFlowsDir)) {
      const copyFlows = (dir, relative = '') => {
        for (const item of fs.readdirSync(dir)) {
          const source = path.join(dir, item);
          const itemRelative = path.join(relative, item);

          if (fs.statSync(source).isDirectory()) {
            copyFlows(source, itemRelative);
            continue;
          }

          const destination = path.join(flowsDir, itemRelative);
          if (fs.existsSync(destination)) { continue; }

          fs.mkdirSync(path.dirname(destination), { recursive: true });
          fs.copyFileSync(source, destination);
          console.log(`Seeded example flow: ${itemRelative}`);
        }
      };

      copyFlows(defaultFlowsDir);
    }

    fs.writeFileSync(markerPath, JSON.stringify({ seededAt: new Date().toISOString() }, null, 2));
  }
  catch (ex) {
    // Seeding must never prevent the tool from starting
    console.error('Could not seed default examples:', ex.message);
  }
};

export {
  ensureDefaults,
  ensureTypeScriptConfig,
  isEmptyDirectory
};
